# Generated by Django 4.2.11 on 2024-04-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
