# Generated by Django 4.2.11 on 2024-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_alter_customer_is_active_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation_code',
            name='code',
            field=models.IntegerField(),
        ),
    ]
