# Generated by Django 4.2.11 on 2024-05-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
        ('grocery_app', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='miniapp.customer'),
        ),
    ]
