# Generated by Django 4.2.11 on 2024-05-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0003_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='user',
            new_name='customer',
        ),
    ]
