# Generated by Django 4.2.11 on 2024-05-18 05:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_app', '0004_rename_user_favourites_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
    ]
