# Generated by Django 4.2.11 on 2024-05-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0005_alter_orderproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='grocery_app.OrderProduct', to='grocery_app.product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='grocery_app.product'),
        ),
    ]
