# Generated by Django 4.2.11 on 2024-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0008_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daily_stock_sold',
            field=models.IntegerField(default=0),
        ),
    ]
