# Generated by Django 4.2.11 on 2024-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0009_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_sold',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=250),
        ),
    ]
