# Generated by Django 4.2.11 on 2024-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0009_product_daily_stock_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='monthly_stock_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weekly_stock_sold',
            field=models.IntegerField(default=0),
        ),
    ]
