# Generated by Django 4.2.11 on 2024-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0010_remove_product_stock_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
